import { properties, type Navigate } from '../data'
import { Icon, type IconName } from './Icon'

export type AdminKind = 'dashboard' | 'listings' | 'reviews' | 'documents' | 'verifications' | 'duplicates' | 'disputes' | 'reports' | 'users' | 'suspensions' | 'deletions' | 'audit' | 'buildings' | 'areas' | 'taxonomy'

const config: Record<AdminKind, { label: string; title: string; text: string; action: string; icon: IconName; variant: 'dashboard' | 'queue' | 'people' | 'audit' | 'catalog' }> = {
  dashboard: { label: 'Control operațional', title: 'Dashboard administrare', text: 'Moderare, verificări, risc și integritatea datelor platformei.', action: 'Deschide coada prioritară', icon: 'chart', variant: 'dashboard' },
  listings: { label: 'Moderare', title: 'Moderare anunțuri', text: 'Listări noi, modificări sensibile și anunțuri semnalate.', action: 'Reguli moderare', icon: 'building', variant: 'queue' },
  reviews: { label: 'Moderare', title: 'Moderare recenzii', text: 'Recenzii noi, contestate și conținut cu risc de date personale.', action: 'Reguli recenzii', icon: 'star', variant: 'queue' },
  documents: { label: 'Verificare', title: 'Documente încărcate', text: 'Fișiere anonimizate și solicitări de completare.', action: 'Politica documentelor', icon: 'file', variant: 'queue' },
  verifications: { label: 'Încredere', title: 'Verificări în lucru', text: 'Identitate, legătura cu proprietatea și sursele datelor.', action: 'Configurează priorități', icon: 'shield', variant: 'queue' },
  duplicates: { label: 'Integritate', title: 'Proprietăți posibil duplicate', text: 'Adrese, anunțuri și dosare care necesită reconciliere.', action: 'Rulează potrivirea', icon: 'compare', variant: 'queue' },
  disputes: { label: 'Cazuri', title: 'Dispute și contestații', text: 'Conflicte privind recenziile, istoricul și dreptul de publicare.', action: 'Politica de soluționare', icon: 'shield', variant: 'queue' },
  reports: { label: 'Siguranță', title: 'Raportări comunitate', text: 'Conținut înșelător, date incorecte și probleme de siguranță.', action: 'Configurează risc', icon: 'file', variant: 'queue' },
  users: { label: 'Utilizatori', title: 'Administrarea utilizatorilor', text: 'Conturi, roluri, verificări și activitate recentă.', action: 'Invită administrator', icon: 'user', variant: 'people' },
  suspensions: { label: 'Siguranță', title: 'Suspendări și restricții', text: 'Conturi restricționate, motive și termene de revizuire.', action: 'Vezi politica', icon: 'shield', variant: 'people' },
  deletions: { label: 'Date personale', title: 'Solicitări de ștergere', text: 'Cereri de acces, portabilitate și ștergere a datelor.', action: 'Exportă raportul', icon: 'file', variant: 'people' },
  audit: { label: 'Trasabilitate', title: 'Jurnal de audit', text: 'Modificări administrative și decizii de moderare.', action: 'Exportă jurnalul', icon: 'history', variant: 'audit' },
  buildings: { label: 'Catalog', title: 'Administrarea blocurilor', text: 'Dosare de clădiri, administratori și potrivirea adreselor.', action: 'Adaugă bloc', icon: 'building', variant: 'catalog' },
  areas: { label: 'Catalog', title: 'Administrarea zonelor', text: 'Sectoare, cartiere, scoruri și puncte de interes.', action: 'Adaugă zonă', icon: 'map', variant: 'catalog' },
  taxonomy: { label: 'Configurare', title: 'Categorii și facilități', text: 'Tipuri de clădiri, facilități, probleme și reguli de afișare.', action: 'Categorie nouă', icon: 'filter', variant: 'catalog' },
}

const adminMenu: Array<[string,string,IconName]> = [['Dashboard','/admin','home'],['Anunțuri','/admin/anunturi','building'],['Recenzii','/admin/recenzii','star'],['Documente','/admin/documente','file'],['Verificări','/admin/verificari','shield'],['Duplicate','/admin/duplicate','compare'],['Dispute','/admin/dispute','shield'],['Raportări','/admin/raportari','file'],['Utilizatori','/admin/utilizatori','user'],['Audit','/admin/audit','history'],['Blocuri','/admin/blocuri','building'],['Zone','/admin/zone','map']]

export function AdminPage({ kind, navigate }: { kind: AdminKind; navigate: Navigate }) {
  const info = config[kind]
  return <div className='admin-page'><div className='admin-shell'>
    <aside className='admin-sidebar'><button className='admin-brand' type='button' onClick={() => navigate('/admin')}><span className='brand-mark'><i /><i /><i /></span><span><strong>Locuința</strong><small>Admin</small></span></button><div className='admin-environment'><span>Mediu demonstrativ</span><b>Operațiuni Chișinău</b></div><nav>{adminMenu.map(([label,path,icon]) => <button className={(kind === 'dashboard' && path === '/admin') || path.endsWith(kind === 'listings' ? 'anunturi' : kind === 'reviews' ? 'recenzii' : kind === 'documents' ? 'documente' : kind === 'verifications' ? 'verificari' : kind) ? 'active' : ''} type='button' onClick={() => navigate(path)} key={path}><Icon name={icon} size={17} /><span>{label}</span>{['Anunțuri','Recenzii','Documente','Verificări'].includes(label) && <b>{[18,12,9,7][['Anunțuri','Recenzii','Documente','Verificări'].indexOf(label)]}</b>}</button>)}</nav><button className='admin-back' type='button' onClick={() => navigate('/dashboard')}><Icon name='arrow-right' className='back-icon' /> Ieși din administrare</button></aside>
    <main className='admin-main'><header className='admin-topbar'><div><button className='admin-menu-button' type='button'><Icon name='menu' /></button><span>Administrare</span><small>/</small><strong>{info.title}</strong></div><div><label><Icon name='search' size={16} /><input placeholder='Caută ID, adresă sau utilizator' /></label><button className='admin-notifications' type='button'><Icon name='shield' /><span>7</span></button><button className='admin-user' type='button'><span>DP</span><div><strong>Dana P.</strong><small>Administrator</small></div></button></div></header>
      <div className='admin-content'><header className='admin-page-header'><div><span><Icon name={info.icon} size={17} /> {info.label}</span><h1>{info.title}</h1><p>{info.text}</p></div><button className='button button-primary' type='button'>{info.action}</button></header>{info.variant === 'dashboard' && <AdminDashboard navigate={navigate} />}{info.variant === 'queue' && <ModerationQueue kind={kind} />}{info.variant === 'people' && <PeopleAdmin kind={kind} />}{info.variant === 'audit' && <AuditLog />}{info.variant === 'catalog' && <CatalogAdmin kind={kind} />}</div>
    </main>
  </div></div>
}

function AdminDashboard({ navigate }: { navigate: Navigate }) { return <div className='admin-dashboard-content'>
  <div className='admin-kpis'>{[['În moderare','46','+8 astăzi'],['Verificări restante','17','4 prioritare'],['Raportări deschise','12','2 risc ridicat'],['Duplicate posibile','9','scor > 85%'],['Timp mediu','3h 24m','−18%']].map(([label,value,note],index) => <article key={label}><span><Icon name={['building','shield','file','compare','clock'][index] as IconName} /></span><div><small>{label}</small><strong>{value}</strong><b>{note}</b></div></article>)}</div>
  <div className='admin-dashboard-grid'><section className='admin-panel moderation-priority'><header><div><h2>Coada prioritară</h2><p>Sortată după risc și timp de așteptare</p></div><button type='button' onClick={() => navigate('/admin/anunturi')}>Vezi coada</button></header>{[['AN-2891','Anunț nou · €118.500','Adresă posibil duplicată','Risc ridicat'],['REC-821','Recenzie nouă','Conține posibil nume complet','Analiză'],['DOC-442','Extras cadastral','Pagina 2 lipsește','Completare'],['REP-117','Raportare comunitate','Fotografii neactuale','Prioritar']].map(([id,title,reason,status]) => <article key={id}><span>{id}</span><div><strong>{title}</strong><small>{reason}</small></div><b>{status}</b><button type='button'>Analizează</button></article>)}</section><section className='admin-panel integrity-panel'><header><div><h2>Sănătatea datelor</h2><p>Ultimele 7 zile</p></div></header><div className='integrity-score'><strong>92%</strong><span>date cu sursă</span></div>{[['Dosare verificate',94],['Adrese normalizate',88],['Prețuri cu sursă',91],['Blocuri complete',76]].map(([label,value]) => <div className='integrity-row' key={label as string}><span>{label as string}</span><i><b style={{width:`${value}%`}} /></i><strong>{value}%</strong></div>)}</section></div>
  <section className='admin-panel admin-activity-chart'><header><div><h2>Activitate de moderare</h2><p>Decizii pe zi și rata de aprobare</p></div><select><option>Ultimele 30 de zile</option></select></header><div><div className='admin-bars'>{[32,45,38,61,54,70,66,82,71,88,79,92,85,76].map((height,index) => <i style={{height:`${height}%`}} key={index} />)}</div><aside><span><b>684</b> decizii</span><span><b>81%</b> aprobate</span><span><b>13%</b> completări</span><span><b>6%</b> respinse</span></aside></div></section>
  </div> }

function ModerationQueue({ kind }: { kind: AdminKind }) { const noun = kind === 'reviews' ? 'recenzie' : kind === 'documents' ? 'document' : kind === 'duplicates' ? 'potrivire' : kind === 'reports' ? 'raportare' : 'anunț'; return <div className='admin-queue'><div className='admin-filters'><div>{['Toate','Prioritare','În așteptare','Necesită completări'].map((item,index) => <button className={index === 0 ? 'active' : ''} type='button' key={item}>{item}</button>)}</div><div><select><option>Orice nivel de risc</option></select><select><option>Toți moderatorii</option></select></div></div><div className='admin-table-head'><span>Selectare</span><span>ID și tip</span><span>Conținut / proprietate</span><span>Semnale</span><span>Timp</span><span>Status</span><span>Acțiuni</span></div>{[0,1,2,3,4].map((item) => <article key={item}><label><input type='checkbox' /></label><span><b>{noun.toUpperCase().slice(0,3)}-{2891-item*137}</b><small>{noun}</small></span><div>{kind === 'listings' && <img src={properties[item%properties.length].image} alt='' />}<span><strong>{kind === 'reviews' ? 'Experiență despre Lev Tolstoi 24/1' : kind === 'documents' ? 'Extras cadastral anonimizat' : properties[item%properties.length].address}</strong><small>{kind === 'documents' ? 'PDF · 2,4 MB' : 'Centru · actualizat recent'}</small></span></div><span className='risk-signals'>{item%2===0 ? 'Posibil duplicat' : 'Sursă incompletă'}</span><span>{item+1}h {item*7}m</span><b className={item===0?'danger':item===1?'warning':'neutral'}>{item===0?'Prioritar':item===1?'Completare':'În analiză'}</b><button type='button'>Deschide</button></article>)}</div> }

function PeopleAdmin({ kind }: { kind: AdminKind }) { return <div className='admin-people'><div className='people-summary'>{[['Conturi active','18.420'],['Verificate','6.284'],[kind === 'deletions' ? 'Cereri deschise' : 'Restricționate',kind === 'deletions' ? '14' : '36'],['Conturi noi azi','82']].map(([label,value]) => <article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div><div className='people-list'><header><span>Utilizator</span><span>Rol</span><span>Verificare</span><span>Activitate</span><span>Status</span><span>Acțiuni</span></header>{[['AM','Ana M.','Căutător','Email','astăzi, 12:42','Activ'],['VI','Victor I.','Proprietar','Identitate + proprietate','astăzi, 11:08','Verificat'],['IC','Irina C.','Agent','Profesional','ieri, 19:20','Verificat'],['DM','Dan M.','Agent','În așteptare','14 iulie','Limitat']].map((row) => <article key={row[1]}><span><b>{row[0]}</b><strong>{row[1]}</strong></span>{row.slice(2).map((cell) => <span key={cell}>{cell}</span>)}<button type='button'>Gestionează</button></article>)}</div></div> }

function AuditLog() { return <div className='audit-log'>{[['12:42:18','Dana P.','AN-2891','A solicitat completarea adresei','Moderare anunț'],['12:31:04','Sistem','LOC-2481','A detectat o posibilă modificare de preț','Regulă automată'],['11:58:22','Mihai R.','REC-821','A mascat o informație personală','Moderare recenzie'],['11:20:11','Dana P.','DOC-442','A confirmat sursa documentului','Verificare'],['10:47:09','Sistem','USR-1821','A aplicat limită temporară','Protecție abuz']].map(([time,user,target,action,type]) => <article key={time}><span>{time}</span><div><strong>{user}</strong><small>{type}</small></div><b>{target}</b><p>{action}</p><button type='button'>Detalii</button></article>)}</div> }

function CatalogAdmin({ kind }: { kind: AdminKind }) { const items = kind === 'buildings' ? [['Toro Center','Centru','184 apartamente','92% complet'],['Oasis Residence','Râșcani','236 apartamente','86% complet'],['Eldorado Terra','Botanica','148 apartamente','78% complet']] : kind === 'areas' ? [['Centru','312 recenzii','4,5 scor','96% complet'],['Râșcani','248 recenzii','4,4 scor','89% complet'],['Botanica','196 recenzii','4,2 scor','83% complet']] : [['Facilități interior','24 opțiuni','3 limbi','Activ'],['Tipuri clădire','12 opțiuni','3 limbi','Activ'],['Probleme raportate','18 categorii','7 severe','Activ']]; return <div className='admin-catalog'><div className='catalog-grid'>{items.map(([title,detail,meta,status],index) => <article key={title}><span><Icon name={kind === 'areas' ? 'map' : kind === 'buildings' ? 'building' : 'filter'} /></span><div><strong>{title}</strong><p>{detail}</p><small>{meta}</small></div><b>{status}</b><button type='button'>Editează</button><div className='catalog-completeness'><i style={{width:`${92-index*8}%`}} /></div></article>)}</div><aside><h3>Calitatea catalogului</h3><p>Elementele incomplete reduc acuratețea căutării și a comparațiilor.</p><div><span>Complete <b>82%</b></span><span>Necesită revizuire <b>14%</b></span><span>Fără sursă <b>4%</b></span></div></aside></div> }
