import { useState } from 'react'
import type { Navigate } from '../data'

interface AuthPageProps { register: boolean; navigate: Navigate; notify: (message: string) => void }

export function AuthPage({ register, navigate, notify }: AuthPageProps) {
  const [tab, setTab] = useState(register ? 'register' : 'login')
  return <div className="auth-page"><section className="auth-benefits"><div><button className="brand brand-static" type="button" onClick={() => navigate('/')}><span className="brand-mark"><i /><i /><i /></span><span><strong>Locuința</strong><small>.md</small></span></button><h1>Decizii imobiliare mai bine informate.</h1><p>Salvează proprietăți, creează alerte, publică anunțuri și urmărește contribuțiile tale.</p><ul><li>Favorite și comparații într-un singur loc</li><li>Alerte pentru prețuri și proprietăți noi</li><li>Dashboard pentru proprietari și agenți</li><li>Recenzii și contribuții verificate</li></ul></div></section><main className="auth-form-wrap"><div className="auth-card"><button className="auth-back" type="button" onClick={() => navigate('/')}>← Înapoi acasă</button><div className="mode-tabs"><button className={tab === 'login' ? 'active' : ''} type="button" onClick={() => setTab('login')}>Intră în cont</button><button className={tab === 'register' ? 'active' : ''} type="button" onClick={() => setTab('register')}>Creează cont</button></div><h2>{tab === 'login' ? 'Bine ai revenit' : 'Creează un cont'}</h2><p>{tab === 'login' ? 'Continuă de unde ai rămas.' : 'Începe cu datele de bază, apoi alegi rolul și preferințele.'}</p>{tab === 'register' && <label>Nume<input placeholder="Numele tău" /></label>}<label>Email<input type="email" placeholder="nume@exemplu.md" /></label><label>Parolă<input type="password" placeholder="Minimum 10 caractere" /></label>{tab === 'register' && <label className="check-line"><input type="checkbox" /> Accept termenii și politica de confidențialitate</label>}<button className="button button-primary button-full" type="button" onClick={() => { notify(tab === 'register' ? 'Cont demonstrativ creat' : 'Autentificare demonstrativă reușită'); navigate(tab === 'register' ? '/onboarding' : '/dashboard') }}>{tab === 'login' ? 'Intră în cont' : 'Creează contul și continuă'}</button><div className="auth-divider"><span>sau</span></div><button className="button button-secondary button-full" type="button" onClick={() => notify('Conectare socială demonstrativă')}>Continuă cu Google</button><button className="forgot-link" type="button" onClick={() => navigate('/parola-uitata')}>Ai uitat parola?</button></div></main></div>
}
