import { galleryImages, properties, recentReviews, type SharedPageProps } from '../data'
import { Icon } from './Icon'
import { PropertyCard } from './PropertyCard'

const buildingFacts = [
  ['An construcție', '2019'], ['Structură', 'Cadru din beton armat'], ['Apartamente', '184'], ['Etaje', '12'],
  ['Ascensoare', '2 · revizie 2026'], ['Parcare', '126 locuri'], ['Administrator', 'Urban Management SRL'], ['Clasă energetică', 'B'],
]

const buildingEvents = [
  ['Feb. 2026', 'Reparație intrare și iluminat', 'Finalizat', 'Confirmat de administrator'],
  ['Nov. 2025', 'Revizie ascensoare', 'Finalizat', 'Verificat prin document'],
  ['Aug. 2025', 'Presiune redusă la apă, etajele 10–12', 'În monitorizare', 'Raportat de comunitate'],
  ['Mai 2024', 'Hidroizolație terasă', 'Finalizat', 'Facturi verificate'],
]

export function BuildingPage(props: SharedPageProps) {
  return (
    <div className='building-page-v2'>
      <div className='container breadcrumb'><button type='button' onClick={() => props.navigate('/')}>Acasă</button><span>/</span><button type='button' onClick={() => props.navigate('/zona/centru')}>Centru</button><span>/</span><strong>Toro Center</strong></div>

      <section className='container building-hero-v2'>
        <div className='building-hero-image'><img src={galleryImages[3].src} alt='Blocul rezidențial Toro Center' /><div><span>Bloc verificat</span><strong>Toro Center</strong><p>str. Lev Tolstoi 24/1 · Centru, Chișinău</p></div></div>
        <div className='building-hero-summary'><span className='eyebrow'>Dosarul clădirii</span><h1>Toro Center</h1><p>Informații structurale, administrare, probleme raportate, prețuri și proprietăți din bloc.</p><div className='building-score'><strong>4,4</strong><span><b>Ratingul blocului</b><small>din 128 de evaluări</small></span></div><div className='building-hero-actions'><button className='button button-primary' type='button' onClick={() => props.navigate('/chirie')}>Vezi apartamente</button><button className='button button-secondary' type='button' onClick={() => props.navigate('/adauga-informatii')}>Adaugă informații</button></div><small className='building-updated'><Icon name='shield' size={16} /> Actualizat la 14 iulie 2026</small></div>
      </section>

      <nav className='entity-anchor-nav'><div className='container'>{['Prezentare', 'Prețuri', 'Apartamente', 'Administrare', 'Probleme', 'Recenzii', 'Comparație'].map((item) => <a href={`#bloc-${item.toLowerCase()}`} key={item}>{item}</a>)}</div></nav>

      <section className='section entity-overview' id='bloc-prezentare'><div className='container'><div className='section-heading'><div><span className='eyebrow'>Clădirea pe scurt</span><h2>Informații structurale și facilități</h2></div><span className='trust-label verified'><Icon name='file' size={15} /> Verificat prin document</span></div><div className='building-fact-grid'>{buildingFacts.map(([label, value]) => <article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div><div className='building-photo-strip'>{galleryImages.map((image) => <img src={image.src} alt={image.alt} key={image.src} />)}</div></div></section>

      <section className='section building-market-section' id='bloc-prețuri'><div className='container building-market-layout'><div className='building-market-copy'><span className='eyebrow'>Analiza prețurilor</span><h2>Cum au evoluat prețurile în bloc.</h2><p>Valorile combină listări active, listări arhivate și tranzacții documentate. Estimările sunt marcate separat.</p><div className='building-market-stats'><div><span>Chirie mediană</span><strong>€640/lună</strong><small className='semantic-positive'>+4,9% în 12 luni</small></div><div><span>Vânzare mediană</span><strong>€1.790/m²</strong><small className='semantic-positive'>+6,2% în 12 luni</small></div><div><span>Tranzacții cunoscute</span><strong>24</strong><small>ultimii 5 ani</small></div></div></div><div className='entity-chart'><div className='chart-head'><span>Preț mediu / m²</span><b>2019–2026</b></div><svg viewBox='0 0 700 260' preserveAspectRatio='none' aria-label='Evoluția prețului pe metru pătrat'><defs><linearGradient id='building-fill' x1='0' y1='0' x2='0' y2='1'><stop offset='0' stopColor='#1768e5' stopOpacity='.25' /><stop offset='1' stopColor='#1768e5' stopOpacity='0' /></linearGradient></defs><path className='entity-chart-area' d='M0 220 C100 210 120 180 210 188 S330 150 410 140 S520 110 585 72 S655 60 700 38 L700 260 L0 260Z' /><path className='entity-chart-line' d='M0 220 C100 210 120 180 210 188 S330 150 410 140 S520 110 585 72 S655 60 700 38' /></svg><div className='entity-chart-axis'><span>2019</span><span>2021</span><span>2023</span><span>2025</span><span>2026</span></div></div></div></section>

      <section className='section building-apartments' id='bloc-apartamente'><div className='container'><div className='section-heading'><div><span className='eyebrow'>În acest bloc</span><h2>Apartamente active</h2></div><button className='text-link' type='button' onClick={() => props.navigate('/chirie')}>Vezi toate <Icon name='arrow-right' size={17} /></button></div><div className='property-grid'>{properties.slice(0, 3).map((property) => <PropertyCard property={property} key={property.id} {...props} />)}</div><div className='historic-apartments'><header><div><h3>Apartamente și tranzacții istorice</h3><p>Înregistrări anonimizate disponibile în dosarul blocului.</p></div><button type='button'>Descarcă sumarul</button></header>{[['Ap. 42 · 2 camere', 'Vândut', 'mart. 2026', '€112.000', '€1.750/m²'], ['Ap. 18 · 3 camere', 'Închiriat', 'ian. 2026', '€780/lună', '24 luni'], ['Ap. 73 · 2 camere', 'Vândut', 'oct. 2025', '€105.500', '€1.690/m²']].map((row) => <div className='historic-apartment-row' key={row[0]}>{row.map((cell, index) => <span key={cell}>{index === 0 ? <strong>{cell}</strong> : cell}</span>)}</div>)}</div></div></section>

      <section className='section building-operations' id='bloc-administrare'><div className='container building-operations-grid'><div><div className='section-heading compact'><div><span className='eyebrow'>Administrare</span><h2>Cine gestionează blocul</h2></div></div><article className='manager-card'><span>UM</span><div><strong>Urban Management SRL</strong><p>Administrator verificat din 2024</p><small>Răspunde în aproximativ 6 ore · rating 4,3/5</small></div><button type='button'>Vezi profilul</button></article><div className='manager-facts'><span>Fond lunar raportat <b>€4.200</b></span><span>Ultima adunare <b>20 iun. 2026</b></span><span>Următoarea revizie <b>sept. 2026</b></span></div></div><div id='bloc-probleme'><div className='section-heading compact'><div><span className='eyebrow'>Întreținere</span><h2>Probleme și reparații</h2></div></div><div className='building-event-list'>{buildingEvents.map(([date, event, status, source]) => <article key={event}><span>{date}</span><div><strong>{event}</strong><small>{source}</small></div><b className={status === 'În monitorizare' ? 'warning' : 'success'}>{status}</b></article>)}</div></div></div></section>

      <section className='section building-reviews' id='bloc-recenzii'><div className='container'><div className='section-heading'><div><span className='eyebrow'>Viața în clădire</span><h2>Ce spun locatarii despre bloc</h2></div><button className='button button-secondary' type='button' onClick={() => props.navigate('/scrie-recenzie')}>Scrie o recenzie</button></div><div className='building-review-grid'>{recentReviews.map((review) => <article key={review.id}><header><span className='avatar'>{review.initials}</span><div><strong>{review.name}</strong><small>{review.role}</small></div><b><Icon name='star' size={15} /> {review.rating}</b></header><p>{review.text}</p><footer><span>Verificat</span><button type='button'>Utilă ({review.helpful})</button></footer></article>)}</div></div></section>

      <section className='section nearby-buildings' id='bloc-comparație'><div className='container'><div className='section-heading'><div><span className='eyebrow'>Reper local</span><h2>Compară cu blocuri apropiate</h2></div></div><div className='nearby-building-grid'>{[['Toro Center', '4,4', '€1.790/m²', '€640'], ['Crown Plaza Park', '4,6', '€1.940/m²', '€710'], ['City Gardens', '4,2', '€1.680/m²', '€590']].map((item, index) => <article className={index === 0 ? 'current' : ''} key={item[0]}><span>{index === 0 ? 'Blocul analizat' : 'La mai puțin de 1 km'}</span><h3>{item[0]}</h3><div><b>★ {item[1]}</b><strong>{item[2]}</strong><small>{item[3]}/lună</small></div></article>)}</div></div></section>
    </div>
  )
}
