import type { Navigate } from '../data'
import { Icon, type IconName } from './Icon'

export type InfoKind =
  | 'about' | 'how' | 'contact' | 'help' | 'faq' | 'safety' | 'fraud' | 'data-verification'
  | 'review-rules' | 'listing-rules' | 'terms' | 'privacy' | 'cookies' | 'data-rights'
  | 'forbidden' | 'not-found' | 'server-error' | 'maintenance' | 'offline' | 'suspended'
  | 'confirm-email' | 'forgot-password' | 'reset-password'

type PageConfig = { eyebrow: string; title: string; text: string; icon: IconName; variant: 'story' | 'guide' | 'contact' | 'legal' | 'status' }

const config: Record<InfoKind, PageConfig> = {
  about: { eyebrow: 'Despre platformă', title: 'Informații mai clare pentru decizii imobiliare mai bune', text: 'Locuința reunește anunțuri, istoric, recenzii și surse într-un dosar ușor de înțeles.', icon: 'building', variant: 'story' },
  how: { eyebrow: 'Ghidul platformei', title: 'Cum funcționează Locuința', text: 'De la prima căutare până la vizionare, ofertă și contribuția la istoricul proprietății.', icon: 'compass', variant: 'guide' },
  contact: { eyebrow: 'Contact', title: 'Spune-ne cu ce te putem ajuta', text: 'Alege subiectul potrivit, iar cererea ajunge direct la echipa responsabilă.', icon: 'message', variant: 'contact' },
  help: { eyebrow: 'Centrul de ajutor', title: 'Găsește rapid răspunsul potrivit', text: 'Ghiduri pentru căutare, publicare, verificare, recenzii și siguranța contului.', icon: 'help', variant: 'guide' },
  faq: { eyebrow: 'Întrebări frecvente', title: 'Răspunsuri directe, fără termeni complicați', text: 'Cele mai importante explicații despre surse, verificare, prețuri și moderare.', icon: 'help', variant: 'guide' },
  safety: { eyebrow: 'Siguranță', title: 'Folosește platforma în siguranță', text: 'Semnale de risc, recomandări pentru vizionări și limitele verificărilor disponibile.', icon: 'shield', variant: 'guide' },
  fraud: { eyebrow: 'Prevenirea fraudelor', title: 'Recunoaște un anunț suspect înainte să plătești', text: 'Câteva verificări simple pot evita avansurile false și identitățile copiate.', icon: 'shield', variant: 'guide' },
  'data-verification': { eyebrow: 'Transparența datelor', title: 'Cum verificăm informațiile', text: 'Fiecare informație importantă păstrează sursa, data și nivelul de încredere.', icon: 'verified', variant: 'guide' },
  'review-rules': { eyebrow: 'Reguli comunitate', title: 'Regulile recenziilor', text: 'Recenziile trebuie să descrie experiențe reale, relevante și respectuoase.', icon: 'star', variant: 'legal' },
  'listing-rules': { eyebrow: 'Reguli publicare', title: 'Regulile anunțurilor', text: 'Cerințe minime pentru fotografii, adresă, preț, reprezentare și disponibilitate.', icon: 'file', variant: 'legal' },
  terms: { eyebrow: 'Documente legale', title: 'Termeni și condiții', text: 'Regulile de utilizare a platformei și responsabilitățile fiecărei părți.', icon: 'file', variant: 'legal' },
  privacy: { eyebrow: 'Documente legale', title: 'Politica de confidențialitate', text: 'Ce date sunt folosite, de ce sunt necesare și ce control ai asupra lor.', icon: 'shield', variant: 'legal' },
  cookies: { eyebrow: 'Preferințe', title: 'Politica privind cookie-urile', text: 'Explicații despre cookie-urile necesare, analitice și opționale.', icon: 'settings', variant: 'legal' },
  'data-rights': { eyebrow: 'Datele tale', title: 'Acces, corectare și ștergere', text: 'Trimite o cerere privind datele contului sau informațiile asociate proprietății.', icon: 'user', variant: 'contact' },
  forbidden: { eyebrow: 'Eroare 403', title: 'Nu ai acces la această pagină', text: 'Pagina este disponibilă doar unui rol sau unui cont cu verificările necesare.', icon: 'shield', variant: 'status' },
  'not-found': { eyebrow: 'Eroare 404', title: 'Pagina nu a fost găsită', text: 'Adresa poate fi greșită, iar pagina poate fi mutată sau retrasă.', icon: 'search', variant: 'status' },
  'server-error': { eyebrow: 'Eroare 500', title: 'A apărut o problemă temporară', text: 'Conținutul nu a putut fi pregătit. Încearcă din nou sau revino la pagina principală.', icon: 'alert', variant: 'status' },
  maintenance: { eyebrow: 'Mentenanță planificată', title: 'Îmbunătățim platforma', text: 'Unele pagini sunt temporar indisponibile. Datele contului rămân în siguranță.', icon: 'settings', variant: 'status' },
  offline: { eyebrow: 'Fără conexiune', title: 'Conexiunea la internet s-a întrerupt', text: 'Verifică rețeaua și încearcă din nou. Modificările netrimise nu au fost salvate.', icon: 'alert', variant: 'status' },
  suspended: { eyebrow: 'Cont restricționat', title: 'Accesul contului este suspendat temporar', text: 'Poți consulta motivul, perioada și pașii disponibili pentru contestație.', icon: 'shield', variant: 'status' },
  'confirm-email': { eyebrow: 'Confirmare cont', title: 'Verifică adresa de e-mail', text: 'Am pregătit un mesaj de confirmare pentru ana@example.com.', icon: 'message', variant: 'status' },
  'forgot-password': { eyebrow: 'Recuperare cont', title: 'Resetează parola', text: 'Introdu adresa contului și îți vom trimite pașii de recuperare.', icon: 'key', variant: 'status' },
  'reset-password': { eyebrow: 'Securitate cont', title: 'Alege o parolă nouă', text: 'Folosește cel puțin 10 caractere și evită parolele folosite pe alte site-uri.', icon: 'key', variant: 'status' },
}

export function InfoPage({ kind, navigate, notify }: { kind: InfoKind; navigate: Navigate; notify: (message: string) => void }) {
  const info = config[kind]
  if (info.variant === 'status') return <StatusPage kind={kind} info={info} navigate={navigate} notify={notify} />
  return <div className={`info-page info-${info.variant}`}>
    <section className='info-hero'><div className='container'><div><span><Icon name={info.icon} size={18} /> {info.eyebrow}</span><h1>{info.title}</h1><p>{info.text}</p></div>{info.variant === 'guide' && <label><Icon name='search' size={19} /><input placeholder='Caută în ghiduri și întrebări' /><button type='button'>Caută</button></label>}</div></section>
    {info.variant === 'story' && <StoryContent navigate={navigate} />}
    {info.variant === 'guide' && <GuideContent kind={kind} navigate={navigate} />}
    {info.variant === 'contact' && <ContactContent kind={kind} notify={notify} />}
    {info.variant === 'legal' && <LegalContent kind={kind} navigate={navigate} />}
  </div>
}

function StoryContent({ navigate }: { navigate: Navigate }) {
  return <>
    <section className='section info-story-intro'><div className='container'><div><span className='section-kicker'>De ce există</span><h2>Un anunț arată momentul. Un dosar explică proprietatea.</h2></div><p>Prețul de astăzi spune puțin fără listările anterioare, renovări, perioade de ocupare, informații despre bloc și experiențele celor care au locuit acolo. Platforma organizează toate aceste semnale și arată clar ce este verificat, estimat sau raportat de comunitate.</p></div></section>
    <section className='section info-principles'><div className='container'><header className='section-heading'><div><span className='section-kicker'>Principiile produsului</span><h2>Conținut util înainte de decor</h2></div></header><div>{[['verified','Sursa rămâne vizibilă','Fiecare fapt important are o origine, o dată și un statut.'],['history','Istoricul nu dispare','Listările, schimbările și contribuțiile formează o cronologie coerentă.'],['shield','Date personale protejate','Perioadele de chirie sunt anonimizate, iar identitățile sensibile nu devin conținut public.'],['compare','Aceleași criterii','Prețurile, costurile, blocul și zona pot fi comparate în aceeași structură.']].map(([icon,title,text]) => <article key={title}><span><Icon name={icon as IconName} /></span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className='section info-roadmap'><div className='container'><div><span className='section-kicker'>Circuitul informației</span><h2>De la contribuție la informație publică</h2><p>Datele demonstrative arată cum ar fi urmărită trasabilitatea într-un produs real.</p><button className='button button-primary' type='button' onClick={() => navigate('/cum-functioneaza')}>Vezi cum funcționează</button></div><div>{[['01','Contribuție','Proprietarul, chiriașul sau comunitatea adaugă informația.'],['02','Verificare','Sursa este analizată și datele personale sunt mascate.'],['03','Context','Informația este legată de proprietate, bloc, zonă și cronologie.'],['04','Publicare','Utilizatorul vede nivelul de încredere și poate raporta o eroare.']].map(([number,title,text]) => <article key={number}><span>{number}</span><div><strong>{title}</strong><p>{text}</p></div></article>)}</div></div></section>
  </>
}

function GuideContent({ kind, navigate }: { kind: InfoKind; navigate: Navigate }) {
  const safety = kind === 'safety' || kind === 'fraud'
  const verification = kind === 'data-verification'
  const guideSteps = safety
    ? [['Nu plăti înainte de vizionare','Evită avansurile cerute prin mesaje urgente sau conturi terțe.'],['Verifică persoana și adresa','Compară identitatea, documentele disponibile și datele anunțului.'],['Păstrează conversația','Folosește mesageria și păstrează confirmările importante.'],['Raportează semnalele','Anunță platforma când prețul, imaginile sau identitatea par copiate.']]
    : verification
      ? [['Document','Sursa a fost analizată, cu datele sensibile ascunse.'],['Confirmare directă','Proprietarul sau chiriașul verificat confirmă informația.'],['Comunitate','Informația este raportată, dar poate necesita dovezi suplimentare.'],['Estimare','Valoarea este calculată orientativ și nu reprezintă o evaluare oficială.']]
      : [['Caută','Alege chirie sau cumpărare și filtrează după nevoile reale.'],['Verifică','Deschide dosarul pentru istoric, recenzii, renovări, bloc și zonă.'],['Compară','Pune alături maximum trei proprietăți pe aceleași criterii.'],['Acționează','Salvează, solicită vizionare, trimite ofertă sau contribuie cu informații.']]
  return <section className='section guide-layout'><div className='container'><aside><strong>În această pagină</strong>{['Primii pași','Înțelegerea datelor','Cont și siguranță','Raportări și corectări'].map((item,index) => <a className={index === 0 ? 'active' : ''} href={`#ghid-${index}`} key={item}>{item}</a>)}<button type='button' onClick={() => navigate('/contact')}>Nu ai găsit răspunsul?</button></aside><div className='guide-content'><section id='ghid-0'><span className='section-kicker'>Pași esențiali</span><h2>{safety ? 'Patru verificări înainte să continui' : verification ? 'Patru niveluri de încredere' : 'Un flux clar de la căutare la decizie'}</h2><div className='guide-step-grid'>{guideSteps.map(([title,text],index) => <article key={title}><span>{index + 1}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section><section id='ghid-1'><span className='section-kicker'>Explicații</span><h2>Întrebări importante</h2><div className='faq-list'>{[['Sunt toate informațiile automat adevărate?','Nu. Eticheta de încredere arată dacă informația este verificată prin document, confirmată, estimată, neverificată sau contestată.'],['De ce poate lipsi istoricul unei proprietăți?','Istoricul se formează în timp din surse și contribuții. Lipsa informației nu înseamnă că un eveniment nu a existat.'],['Pot cere corectarea unei informații?','Da. Fiecare dosar are acțiune de raportare, iar contul păstrează starea solicitării de corectare.'],['Sunt afișate numele chiriașilor?','Nu. Perioadele de ocupare sunt anonimizate, iar recenziile păstrează doar relația verificată cu proprietatea.']].map(([question,answer],index) => <details open={index === 0} key={question}><summary>{question}<Icon name='chevron-down' size={17} /></summary><p>{answer}</p></details>)}</div></section><section id='ghid-2' className='guide-callout'><Icon name='shield' size={28} /><div><h3>Nicio insignă nu înlocuiește verificarea personală</h3><p>Vizitează proprietatea, citește documentele potrivite situației și cere ajutor profesionist înainte de o tranzacție.</p></div></section></div></div></section>
}

function ContactContent({ kind, notify }: { kind: InfoKind; notify: (message: string) => void }) {
  const rights = kind === 'data-rights'
  return <section className='section contact-layout'><div className='container'><aside><h2>{rights ? 'Înainte de trimitere' : 'Canale potrivite pentru fiecare situație'}</h2><p>{rights ? 'Verificăm identitatea pentru a proteja informațiile contului și ale proprietăților.' : 'Pentru probleme urgente de siguranță folosește direct raportarea din anunț.'}</p><div>{[['message','Asistență generală','Răspuns demonstrativ în 1–2 zile lucrătoare'],['shield','Siguranță și fraudă','Cazurile urgente primesc prioritate'],['file','Date și documente','Acces limitat echipei de verificare']].map(([icon,title,text]) => <article key={title}><Icon name={icon as IconName} /><span><strong>{title}</strong><small>{text}</small></span></article>)}</div></aside><form onSubmit={(event) => { event.preventDefault(); notify(rights ? 'Cererea privind datele a fost înregistrată' : 'Mesajul demonstrativ a fost trimis') }}><div className='form-heading'><span className='section-kicker'>{rights ? 'Cerere privind datele' : 'Formular de contact'}</span><h2>{rights ? 'Ce dorești să soliciți?' : 'Descrie situația'}</h2></div><div className='contact-form-grid'><label>Subiect<select defaultValue=''><option value='' disabled>Alege subiectul</option><option>{rights ? 'Acces la date' : 'Ajutor cu o proprietate'}</option><option>{rights ? 'Corectarea datelor' : 'Raportare sau siguranță'}</option><option>{rights ? 'Ștergerea datelor' : 'Cont și verificare'}</option></select></label><label>Adresa de e-mail<input type='email' defaultValue='ana@example.com' /></label><label className='full'>Referință opțională<input placeholder='ID proprietate, anunț sau solicitare' /></label><label className='full'>Mesaj<textarea placeholder='Include informațiile necesare, fără date personale care nu sunt relevante.' /></label><label className='full contact-consent'><input type='checkbox' defaultChecked /><span>Confirm că informațiile sunt corecte și pot fi folosite pentru analizarea cererii.</span></label></div><button className='button button-primary' type='submit'>{rights ? 'Trimite cererea' : 'Trimite mesajul'}</button></form></div></section>
}

function LegalContent({ kind, navigate }: { kind: InfoKind; navigate: Navigate }) {
  const titles = kind === 'review-rules' ? ['Experiențe autentice','Date personale','Conținut interzis','Moderare și contestații'] : kind === 'listing-rules' ? ['Dreptul de publicare','Acuratețea anunțului','Fotografii și adresă','Disponibilitate și actualizare'] : kind === 'privacy' ? ['Date colectate','Scop și temei','Partajare și protecție','Drepturile tale'] : kind === 'cookies' ? ['Necesare','Preferințe','Analiză','Controlul cookie-urilor'] : ['Utilizarea serviciului','Conținut și contribuții','Limitarea răspunderii','Suspendare și încetare']
  return <section className='section legal-layout'><div className='container'><aside><span>Actualizat la 16 iulie 2026</span>{titles.map((title,index) => <a href={`#legal-${index}`} key={title}>{index + 1}. {title}</a>)}<button type='button' onClick={() => navigate('/contact')}>Întrebări despre document</button></aside><article><div className='legal-note'><Icon name='info' /><p>Acest ecran este conținut demonstrativ pentru prezentarea UI/UX și nu reprezintă consultanță juridică sau un document final aprobat.</p></div>{kind === 'cookies' && <div className='cookie-preferences'><header><div><span className='section-kicker'>Control direct</span><h2>Preferințele cookie-urilor</h2></div><span>Salvare demonstrativă</span></header>{[['Necesare','Mențin sesiunea și funcțiile de bază. Nu pot fi dezactivate.',true,true],['Preferințe','Păstrează limba, vizualizarea și filtrele alese.',true,false],['Analiză','Ajută la înțelegerea folosirii paginilor, în mod agregat.',false,false],['Personalizare','Adaptează recomandările pe baza activității.',false,false]].map(([title,text,checked,locked]) => <label key={title as string}><div><strong>{title as string}</strong><p>{text as string}</p></div><input type='checkbox' defaultChecked={checked as boolean} disabled={locked as boolean} /><span /></label>)}<footer><button type='button'>Respinge opționalele</button><button className='button button-primary' type='button'>Salvează preferințele</button></footer></div>}{titles.map((title,index) => <section id={`legal-${index}`} key={title}><span>{String(index + 1).padStart(2,'0')}</span><div><h2>{title}</h2><p>Platforma solicită informații relevante, corecte și proporționale cu scopul declarat. Conținutul important trebuie să poată fi explicat printr-o sursă sau o experiență directă.</p><p>Informațiile sensibile sunt limitate, mascate sau eliminate înainte de afișarea publică. Utilizatorul poate raporta o eroare și poate solicita revizuirea unei decizii.</p>{index === 1 && <ul><li>Nu publica date complete despre chiriași sau documente neanonimizate.</li><li>Nu afirma că o estimare este o evaluare oficială.</li><li>Nu încărca fotografii asupra cărora nu ai drepturi.</li></ul>}</div></section>)}</article></div></section>
}

function StatusPage({ kind, info, navigate, notify }: { kind: InfoKind; info: PageConfig; navigate: Navigate; notify: (message: string) => void }) {
  const isForm = kind === 'forgot-password' || kind === 'reset-password'
  return <div className={`status-page status-${kind}`}><div className='status-card'><button className='status-brand' type='button' onClick={() => navigate('/')}><span className='brand-mark'><i /><i /><i /></span><strong>Locuința</strong></button><div className='status-icon'><Icon name={info.icon} size={30} /></div><span className='status-eyebrow'>{info.eyebrow}</span><h1>{info.title}</h1><p>{info.text}</p>{isForm && <form onSubmit={(event) => { event.preventDefault(); notify(kind === 'forgot-password' ? 'Linkul demonstrativ a fost pregătit' : 'Parola demonstrativă a fost actualizată') }}>{kind === 'forgot-password' ? <label>Adresa de e-mail<input type='email' placeholder='nume@exemplu.md' /></label> : <><label>Parola nouă<input type='password' placeholder='Cel puțin 10 caractere' /></label><label>Confirmă parola<input type='password' placeholder='Repetă parola' /></label></>}<button className='button button-primary' type='submit'>{kind === 'forgot-password' ? 'Trimite linkul de resetare' : 'Salvează parola'}</button></form>}{kind === 'suspended' && <div className='suspension-detail'><span><small>Motiv</small><strong>Verificare suplimentară necesară</strong></span><span><small>Revizuire</small><strong>18 iulie 2026</strong></span></div>}{kind === 'confirm-email' && <button className='button button-primary' type='button' onClick={() => notify('Mesajul de confirmare a fost retrimis')}>Retrimite mesajul</button>}<div className='status-actions'><button type='button' onClick={() => navigate('/')}>Pagina principală</button>{!isForm && kind !== 'confirm-email' && <button type='button' onClick={() => kind === 'offline' ? window.location.reload() : navigate('/contact')}>{kind === 'offline' ? 'Încearcă din nou' : 'Cere ajutor'}</button>}</div><small className='status-reference'>Referință demonstrativă · LOC-{kind.toUpperCase().slice(0,4)}-2026</small></div></div>
}
