import { useState } from 'react'
import type { Navigate } from '../data'
import { Icon } from './Icon'

type OnboardingRole = 'seeker' | 'owner' | 'agent'

const copy = {
  seeker: { label: 'Configurare căutare', title: 'Găsește mai repede locuința potrivită.', text: 'Spune-ne ce cauți pentru recomandări și alerte relevante.', steps: ['Obiectiv', 'Zone', 'Buget și nevoi', 'Alerte'] },
  owner: { label: 'Configurare proprietar', title: 'Pregătește spațiul tău de proprietar.', text: 'Confirmă rolul, proprietățile și modul în care vrei să primești cereri.', steps: ['Rol', 'Proprietăți', 'Verificare', 'Contact'] },
  agent: { label: 'Configurare agent', title: 'Configurează portofoliul și agenția.', text: 'Setează profilul public, zonele și colaborarea cu echipa.', steps: ['Profil', 'Agenție', 'Portofoliu', 'Verificare'] },
} satisfies Record<OnboardingRole, { label: string; title: string; text: string; steps: string[] }>

export function OnboardingPage({ role, navigate }: { role: OnboardingRole; navigate: Navigate }) {
  const [step, setStep] = useState(0)
  const info = copy[role]

  return <div className={`onboarding-page onboarding-${role}`}><div className='onboarding-shell'>
    <aside><button type='button' onClick={() => navigate('/')}><span className='brand-mark'><i /><i /><i /></span><strong>Locuința.md</strong></button><div><span>{info.label}</span><h1>{info.title}</h1><p>{info.text}</p></div><blockquote>„Istoricul proprietății și sursele verificate m-au ajutat să decid cu mai multă încredere.”<small>Utilizator verificat</small></blockquote></aside>
    <main><header><span>Pasul {step + 1} din {info.steps.length}</span><button type='button' onClick={() => navigate('/dashboard')}>Continuă mai târziu</button></header><div className='onboarding-progress'>{info.steps.map((item,index) => <div className={index === step ? 'active' : index < step ? 'done' : ''} key={item}><span>{index < step ? <Icon name='check' size={15} /> : index + 1}</span><strong>{item}</strong></div>)}</div><section><OnboardingStep role={role} step={step} /></section><footer><button type='button' disabled={step === 0} onClick={() => setStep((current) => Math.max(0,current-1))}>Înapoi</button><button className='button button-primary' type='button' onClick={() => step === info.steps.length - 1 ? navigate('/dashboard') : setStep((current) => current + 1)}>{step === info.steps.length - 1 ? 'Finalizează configurarea' : 'Continuă'} <Icon name='arrow-right' size={17} /></button></footer></main>
  </div></div>
}

function OnboardingStep({ role, step }: { role: OnboardingRole; step: number }) {
  if (role === 'seeker') {
    if (step === 0) return <><span className='step-label'>Ce vrei să faci?</span><h2>Alege obiectivul principal.</h2><div className='onboarding-choices two'><button className='active' type='button'><Icon name='key' /><strong>Vreau să închiriez</strong><p>Recomandări după buget, condiții și istoric.</p></button><button type='button'><Icon name='home' /><strong>Vreau să cumpăr</strong><p>Analiză de preț, tranzacții și comparație cu zona.</p></button></div></>
    if (step === 1) return <><span className='step-label'>Unde cauți?</span><h2>Selectează sectoarele preferate.</h2><div className='onboarding-chips'>{['Centru','Râșcani','Botanica','Buiucani','Ciocana','Telecentru'].map((item,index) => <button className={index < 2 ? 'active' : ''} type='button' key={item}>{item}</button>)}</div><label className='onboarding-field'>Complexe sau străzi preferate<input placeholder='Ex. Toro Center, str. Lev Tolstoi' /></label></>
    if (step === 2) return <><span className='step-label'>Criterii</span><h2>Definește bugetul și nevoile.</h2><div className='onboarding-form-grid'><label>Buget minim<input defaultValue='€450' /></label><label>Buget maxim<input defaultValue='€700' /></label><label>Camere<select><option>2 camere</option></select></label><label>Suprafață minimă<input defaultValue='55 m²' /></label></div><div className='onboarding-checks'>{['Mobilat','Animale acceptate','Parcare','Ascensor','Cu istoric','Doar verificate'].map((item) => <label key={item}><input type='checkbox' defaultChecked /><span><Icon name='check' size={14} /></span>{item}</label>)}</div></>
    return <><span className='step-label'>Rămâi la curent</span><h2>Cum vrei să primești alertele?</h2><div className='alert-preference'><label><input type='radio' name='alert' defaultChecked /><span><strong>Instant</strong><small>Când apare o proprietate foarte potrivită</small></span></label><label><input type='radio' name='alert' /><span><strong>Rezumat zilnic</strong><small>O notificare în fiecare dimineață</small></span></label><label><input type='radio' name='alert' /><span><strong>Rezumat săptămânal</strong><small>Pentru o căutare mai relaxată</small></span></label></div></>
  }
  if (role === 'owner') {
    if (step === 0) return <><span className='step-label'>Rolul tău</span><h2>Cum gestionezi proprietatea?</h2><div className='onboarding-choices two'><button className='active' type='button'><Icon name='user' /><strong>Sunt proprietar</strong><p>Public și gestionez direct proprietatea.</p></button><button type='button'><Icon name='file' /><strong>Am procură</strong><p>Administrez proprietatea pentru altcineva.</p></button></div></>
    if (step === 1) return <><span className='step-label'>Evităm duplicatele</span><h2>Caută proprietățile existente.</h2><label className='onboarding-search'><Icon name='search' /><input defaultValue='str. Lev Tolstoi 24/1' /><button type='button'>Caută</button></label><div className='possible-match'><Icon name='building' /><span><strong>Am găsit o proprietate posibilă</strong><small>str. Lev Tolstoi 24/1 · ap. 47</small></span><button type='button'>Revendică</button></div></>
    if (step === 2) return <><span className='step-label'>Încredere</span><h2>Pregătește verificarea.</h2><div className='verification-guide'>{[['Identitate','Buletin sau semnătură electronică'],['Legătura cu proprietatea','Extras, contract sau procură'],['Date protejate','Poți masca seria și datele personale']].map(([title,text],index) => <article key={title}><span>{index+1}</span><div><strong>{title}</strong><p>{text}</p></div></article>)}</div><button className='document-upload' type='button'><Icon name='plus' /><span><strong>Încarcă primul document</strong><small>PDF, JPG sau PNG · maximum 15 MB</small></span></button></>
    return <><span className='step-label'>Contact și vizionări</span><h2>Stabilește cum vei răspunde.</h2><div className='onboarding-form-grid'><label>Telefon<input defaultValue='+373 6xx xxx xx' /></label><label>Email<input defaultValue='victor@example.md' /></label><label>Interval de contact<select><option>09:00–19:00</option></select></label><label>Timp estimat de răspuns<select><option>În aproximativ 2 ore</option></select></label></div></>
  }
  if (step === 0) return <><span className='step-label'>Profil profesional</span><h2>Cum vei apărea public?</h2><div className='onboarding-form-grid'><label>Nume public<input defaultValue='Irina C.' /></label><label>Telefon profesional<input defaultValue='+373 6xx xxx xx' /></label><label className='full'>Descriere<textarea defaultValue='Consultant imobiliar specializat în Centru și Râșcani.' /></label></div></>
  if (step === 1) return <><span className='step-label'>Agenție</span><h2>Lucrezi individual sau într-o echipă?</h2><div className='onboarding-choices two'><button type='button'><Icon name='user' /><strong>Agent independent</strong><p>Gestionez propriul portofoliu.</p></button><button className='active' type='button'><Icon name='building' /><strong>Casa Nouă Imobil</strong><p>Agenție găsită și verificată în platformă.</p></button></div></>
  if (step === 2) return <><span className='step-label'>Specializare</span><h2>Configurează portofoliul.</h2><div className='onboarding-chips'>{['Chirie','Vânzare','Centru','Râșcani','Blocuri noi','Investiții'].map((item) => <button className='active' type='button' key={item}>{item}</button>)}</div><div className='onboarding-form-grid'><label>Proprietăți active<input defaultValue='24' /></label><label>Experiență<select><option>5–10 ani</option></select></label></div></>
  return <><span className='step-label'>Verificare profesională</span><h2>Confirmă identitatea și agenția.</h2><div className='verification-guide'>{[['Identitate agent','În așteptare'],['Date agenție','Confirmate'],['Contract de colaborare','Necesar']].map(([title,status],index) => <article key={title}><span>{index+1}</span><div><strong>{title}</strong><p>{status}</p></div></article>)}</div><button className='document-upload' type='button'><Icon name='plus' /><span><strong>Încarcă documentul de colaborare</strong><small>Datele personale nu vor fi publice</small></span></button></>
}
