import { properties, recentReviews, type SharedPageProps } from '../data'
import { Icon } from './Icon'
import { PropertyCard } from './PropertyCard'

export function PublicProfessionalPage({ kind, ...shared }: SharedPageProps & { kind: 'agent' | 'agency' }) {
  const agency = kind === 'agency'
  return <div className='professional-page'>
    <div className='container breadcrumb'><button type='button' onClick={() => shared.navigate('/')}>Acasă</button><span>/</span><strong>{agency ? 'Casa Nouă Imobil' : 'Irina C.'}</strong></div>
    <section className={`professional-hero ${agency ? 'agency' : 'agent'}`}><div className='container professional-hero-layout'><div className='professional-identity'><span className='professional-avatar'>{agency ? 'CN' : 'IC'}</span><div><span className='trust-label verified'><Icon name='shield' size={15} /> {agency ? 'Agenție verificată' : 'Agent verificat'}</span><h1>{agency ? 'Casa Nouă Imobil' : 'Irina C.'}</h1><p>{agency ? 'Agenție imobiliară din Chișinău · activă din 2016' : 'Consultant imobiliar · Centru și Râșcani · 8 ani experiență'}</p><div className='professional-rating'><b><Icon name='star' size={16} /> {agency ? '4,7' : '4,8'}</b><span>{agency ? '184 recenzii' : '62 recenzii'}</span><span>Răspunde în aproximativ {agency ? '35 min' : '1 oră'}</span></div></div></div><div className='professional-actions'><button className='button button-primary' type='button' onClick={() => shared.notify('Mesajul a fost pregătit')}>Trimite mesaj</button><button className='button button-secondary' type='button' onClick={() => shared.navigate('/portofoliu')}>Vezi portofoliul</button></div></div></section>
    <nav className='entity-anchor-nav'><div className='container'>{['Despre', 'Portofoliu', agency ? 'Echipă' : 'Experiență', 'Recenzii', 'Verificare'].map((item) => <a href={`#pro-${item.toLowerCase()}`} key={item}>{item}</a>)}</div></nav>
    <section className='section professional-about' id='pro-despre'><div className='container professional-about-layout'><div><span className='eyebrow'>Profil public</span><h2>{agency ? 'O echipă pentru tranzacții transparente.' : 'Consultanță directă, cu proprietăți documentate.'}</h2><p>{agency ? 'Lucrăm cu proprietari și cumpărători din Chișinău, folosind date despre preț, istoric și surse pentru fiecare proprietate din portofoliu.' : 'Ajut cumpărătorii și chiriașii să compare proprietăți pe baza istoricului, costurilor reale și informațiilor despre bloc și zonă.'}</p><div className='specialization-chips'>{['Centru','Râșcani','Blocuri noi','Vânzare','Chirie','Investiții'].map((item) => <span key={item}>{item}</span>)}</div></div><div className='professional-facts'>{(agency ? [['Proprietăți active','46'],['Agenți verificați','9'],['Tranzacții încheiate','218'],['Timp mediu de răspuns','35 min'],['Rată de verificare','96%'],['Limbi','RO · RU · EN']] : [['Proprietăți active','12'],['Tranzacții încheiate','74'],['Vizionări realizate','286'],['Timp mediu de răspuns','1 oră'],['Rată de verificare','98%'],['Limbi','RO · RU · EN']]).map(([label,value]) => <article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div></div></section>
    <section className='section professional-portfolio' id='pro-portofoliu'><div className='container'><div className='section-heading'><div><span className='eyebrow'>Portofoliu activ</span><h2>Proprietăți reprezentate</h2></div><button className='text-link' type='button' onClick={() => shared.navigate('/portofoliu')}>Toate proprietățile <Icon name='arrow-right' size={17} /></button></div><div className='property-grid'>{properties.slice(0,3).map((property) => <PropertyCard property={property} key={property.id} {...shared} />)}</div></div></section>
    <section className='section professional-team' id={agency ? 'pro-echipă' : 'pro-experiență'}><div className='container'><div className='section-heading'><div><span className='eyebrow'>{agency ? 'Echipa' : 'Experiență'}</span><h2>{agency ? 'Agenți verificați și specializați.' : 'Activitate și rezultate recente.'}</h2></div></div>{agency ? <div className='professional-member-grid'>{[['IC','Irina C.','Agent senior','12 proprietăți'],['DM','Dan M.','Consultant vânzări','9 proprietăți'],['AP','Ana P.','Consultant chirii','8 proprietăți'],['RC','Radu C.','Evaluare și investiții','6 proprietăți']].map(([initials,name,role,count]) => <article key={name}><span>{initials}</span><strong>{name}</strong><p>{role}</p><small>{count}</small><button type='button' onClick={() => shared.navigate(`/agent/${name.toLocaleLowerCase('ro-RO').replaceAll(' ', '-').replaceAll('.', '')}`)}>Vezi profilul</button></article>)}</div> : <div className='professional-timeline'>{[['2018','Început activitatea','Consultant pentru proprietăți rezidențiale'],['2021','Specializare Centru și Râșcani','Peste 30 de tranzacții documentate'],['2024','Agent verificat Locuința.md','Identitate și portofoliu confirmate'],['2026','74 tranzacții încheiate','Rating public 4,8 din 62 recenzii']].map(([year,title,text]) => <article key={year}><span>{year}</span><div><strong>{title}</strong><p>{text}</p></div></article>)}</div>}</div></section>
    <section className='section professional-reviews' id='pro-recenzii'><div className='container'><div className='section-heading'><div><span className='eyebrow'>Încredere publică</span><h2>Recenzii de la clienți verificați</h2></div></div><div className='professional-review-grid'>{recentReviews.map((review) => <article key={review.id}><header><span className='avatar'>{review.initials}</span><div><strong>{review.name}</strong><small>{review.role}</small></div><b><Icon name='star' size={15} /> {review.rating}</b></header><p>{review.text}</p><footer>Verificat prin document · {review.period}</footer></article>)}</div></div></section>
    <section className='professional-verification' id='pro-verificare'><div className='container'><div><Icon name='shield' size={32} /><span><strong>{agency ? 'Agenție verificată' : 'Identitate și portofoliu verificate'}</strong><p>{agency ? 'Date juridice, membri și documente de reprezentare confirmate.' : 'Identitatea profesională și legătura cu proprietățile au fost confirmate.'}</p></span></div><button type='button' onClick={() => shared.navigate('/cum-functioneaza')}>Cum funcționează verificarea</button></div></section>
  </div>
}
