import { useState } from 'react'
import type { SharedPageProps } from '../data'
import { Icon, type IconName } from './Icon'

const trustLevels: Array<[string,string]> = [
  ['verified','Verificat prin document'],['owner','Confirmat de proprietar'],['tenant','Confirmat de chiriaș'],['community','Raportat de comunitate'],['estimate','Estimare'],['unverified','Neverificat'],['disputed','Contestat'],
]

export function UIStatesPage({ navigate, notify }: SharedPageProps) {
  const [reportOpen,setReportOpen] = useState(false)
  const [toastDemo,setToastDemo] = useState<'alert'|'success'>('alert')
  return <div className='ui-states-page'>
    <section className='ui-states-hero'><div className='container'><div><span><Icon name='settings' size={18} /> Sistem UI demonstrativ</span><h1>Stări clare pentru fiecare situație.</h1><p>Exemple complete pentru încărcare, lipsa datelor, erori, formulare, upload, transparență și confirmări.</p></div><button className='button button-secondary' type='button' onClick={() => navigate('/cum-verificam-datele')}>Vezi metodologia datelor</button></div></section>
    <nav className='states-anchor-nav'><div className='container'>{['Încărcare','Stări goale','Erori','Formulare','Încredere','Feedback'].map((item,index) => <a href={`#state-${index}`} key={item}>{item}</a>)}</div></nav>
    <section className='section states-showcase'><div className='container'>
      <StateGroup id='state-0' label='01 · Încărcare' title='Conținutul își păstrează structura în timp ce se pregătește'><div className='state-demo-grid two'><article className='state-surface'><StateHeader icon='clock' title='Listă în încărcare' tag='Skeleton' /><div className='listing-skeleton-demo'>{[0,1,2].map((item) => <div key={item}><i /><span><b /><b /><b /></span></div>)}</div></article><article className='state-surface'><StateHeader icon='map' title='Hartă în încărcare' tag='Loading' /><div className='map-loading-demo'><div className='state-spinner' /><strong>Se pregătesc proprietățile…</strong><small>Harta rămâne în aceeași poziție</small></div></article></div></StateGroup>
      <StateGroup id='state-1' label='02 · Stări goale' title='Lipsa conținutului explică următorul pas'><div className='state-demo-grid three'>{[
        ['search','Niciun rezultat','Modifică prețul sau elimină un filtru pentru a vedea mai multe proprietăți.','Resetează filtrele'],
        ['filter','Filtrele nu se potrivesc','Încearcă fără „renovare recentă” sau mărește suprafața maximă.','Editează filtrele'],
        ['star','Încă nu există recenzii','Poți fi prima persoană care descrie o experiență verificabilă.','Scrie o recenzie'],
        ['history','Istoric necunoscut','Nu au fost adăugate evenimente. Absența datelor nu confirmă lipsa lor.','Adaugă informații'],
        ['heart','Colecție goală','Salvează proprietăți pentru a le compara sau urmări schimbările.','Explorează proprietăți'],
        ['file','Upload gol','Adaugă documentul doar dacă este relevant și anonimizat.','Alege un fișier'],
      ].map(([icon,title,text,action]) => <article className='state-empty-card' key={title}><span><Icon name={icon as IconName} /></span><h3>{title}</h3><p>{text}</p><button type='button'>{action}</button></article>)}</div></StateGroup>
      <StateGroup id='state-2' label='03 · Erori și indisponibilitate' title='Problema, efectul și ieșirea sunt vizibile împreună'><div className='state-demo-grid three'>{[
        ['alert','Nu am putut încărca rezultatele','Conexiunea a fost întreruptă. Filtrele selectate au fost păstrate.','Încearcă din nou','error'],
        ['building','Proprietate indisponibilă','Anunțul nu mai acceptă cereri, dar dosarul istoric rămâne vizibil.','Vezi dosarul','warning'],
        ['shield','Date neverificate','Prețul a fost raportat de comunitate și nu are încă o sursă confirmată.','Vezi sursa','neutral'],
      ].map(([icon,title,text,action,tone]) => <article className={`state-error-card ${tone}`} key={title}><span><Icon name={icon as IconName} /></span><div><h3>{title}</h3><p>{text}</p><button type='button'>{action}</button></div></article>)}</div></StateGroup>
      <StateGroup id='state-3' label='04 · Formulare și upload' title='Validarea apare lângă informația care trebuie corectată'><div className='state-demo-grid two'><article className='state-surface'><StateHeader icon='file' title='Formular incomplet' tag='Necesită atenție' /><div className='incomplete-form-demo'><label>Adresa<input value='str. Lev Tolstoi' readOnly /><small><Icon name='alert' size={13} /> Adaugă numărul blocului.</small></label><label>Suprafață<input placeholder='Exemplu: 64 m²' /><small><Icon name='alert' size={13} /> Acest câmp este obligatoriu.</small></label><button className='button button-primary' type='button' disabled>Continuă</button></div></article><article className='state-surface'><StateHeader icon='renovation' title='Încărcarea fotografiilor' tag='Gol / reușit' /><div className='upload-state-demo'><button type='button'><Icon name='plus' /><strong>Adaugă fotografii</strong><small>JPG sau PNG · maximum 15 MB</small></button><div><span><Icon name='check' /> living-principal.jpg</span><strong>Încărcare reușită</strong><small>2,8 MB · imagine principală</small></div></div></article></div></StateGroup>
      <StateGroup id='state-4' label='05 · Încredere și transparență' title='Aceleași etichete pentru toate informațiile importante'><div className='trust-state-panel'><div>{trustLevels.map(([tone,label]) => <span className={`trust-label ${tone}`} key={label}>{label}</span>)}</div><article><Icon name='info' /><div><strong>Eticheta descrie sursa, nu garantează rezultatul</strong><p>O informație verificată confirmă legătura cu sursa analizată. Utilizatorul trebuie să consulte contextul și data.</p></div></article></div></StateGroup>
      <StateGroup id='state-5' label='06 · Feedback și confirmări' title='Acțiunile importante primesc răspuns vizual imediat'><div className='state-demo-grid two'><article className='state-surface'><StateHeader icon='message' title='Mesaje inline' tag='Alertă / confirmare' /><div className={`feedback-demo ${toastDemo}`}><Icon name={toastDemo === 'alert' ? 'alert' : 'check'} /><div><strong>{toastDemo === 'alert' ? 'Informații lipsă' : 'Modificări salvate'}</strong><p>{toastDemo === 'alert' ? 'Completează anul construcției înainte de trimitere.' : 'Draftul poate fi continuat din „Anunțurile mele”.'}</p></div></div><div className='feedback-switch'><button className={toastDemo === 'alert' ? 'active' : ''} type='button' onClick={() => setToastDemo('alert')}>Alertă</button><button className={toastDemo === 'success' ? 'active' : ''} type='button' onClick={() => setToastDemo('success')}>Confirmare</button></div></article><article className='state-surface report-demo'><StateHeader icon='shield' title='Raportare' tag='Modal' /><p>Raportarea creează un caz separat și nu schimbă automat informația publică.</p><button className='button button-secondary' type='button' onClick={() => setReportOpen(true)}>Deschide modalul</button></article></div></StateGroup>
    </div></section>
    {reportOpen && <div className='modal-backdrop' role='dialog' aria-modal='true' aria-labelledby='state-report-title'><form className='form-modal' onSubmit={(event) => { event.preventDefault(); setReportOpen(false); notify('Raportarea demonstrativă a fost trimisă') }}><button className='modal-close' type='button' aria-label='Închide' onClick={() => setReportOpen(false)}><Icon name='close' size={17} /></button><span className='section-kicker'>Siguranța comunității</span><h2 id='state-report-title'>Raportează o informație</h2><p>Alege motivul și descrie exact ce pare incorect.</p><label>Motiv<select><option>Preț incorect</option><option>Fotografii neactuale</option><option>Date personale</option><option>Conținut înșelător</option></select></label><label>Detalii<textarea placeholder='Descrie problema fără date personale inutile.' /></label><div className='modal-form-actions'><button type='button' onClick={() => setReportOpen(false)}>Anulează</button><button className='button button-primary' type='submit'>Trimite raportarea</button></div></form></div>}
  </div>
}

function StateHeader({ icon,title,tag }: { icon: IconName; title: string; tag: string }) { return <header className='state-card-header'><span><Icon name={icon} /></span><div><strong>{title}</strong><small>{tag}</small></div></header> }

function StateGroup({ id,label,title,children }: { id: string; label: string; title: string; children: React.ReactNode }) { return <section className='state-group' id={id}><header><span className='section-kicker'>{label}</span><h2>{title}</h2></header>{children}</section> }
