import { properties, type SharedPageProps } from '../data'
import { Icon, type IconName } from './Icon'
import { PropertyCard } from './PropertyCard'

export type WorkspaceKind = 'recommendations' | 'recent' | 'browsing' | 'collections' | 'alert-detail' | 'visit-detail' | 'my-offers' | 'my-reports' | 'corrections' | 'claim' | 'property-verification' | 'listing-performance' | 'leads' | 'requests' | 'owner-offers' | 'calendar' | 'review-responses' | 'disputes' | 'documents' | 'owner-profile' | 'archive' | 'listing-status' | 'portfolio' | 'agent-leads' | 'members' | 'roles' | 'agency-stats' | 'agency-verification'
type Role = 'seeker' | 'owner' | 'agent'
type Variant = 'properties' | 'activity' | 'collections' | 'alert' | 'calendar' | 'cases' | 'verification' | 'stats' | 'table' | 'pipeline' | 'profile'

interface PageInfo { role: Role; label: string; title: string; description: string; action: string; variant: Variant }

const pages: Record<WorkspaceKind, PageInfo> = {
  recommendations: { role: 'seeker', label: 'Descoperire', title: 'Recomandări pentru tine', description: 'Proprietăți ordonate după criteriile, favoritele și alertele tale.', action: 'Ajustează preferințele', variant: 'properties' },
  recent: { role: 'seeker', label: 'Activitate', title: 'Vizualizate recent', description: 'Continuă analiza proprietăților deschise în ultimele zile.', action: 'Șterge lista', variant: 'properties' },
  browsing: { role: 'seeker', label: 'Activitate', title: 'Istoric de navigare', description: 'Căutări, filtre și proprietăți consultate, grupate cronologic.', action: 'Șterge istoricul', variant: 'activity' },
  collections: { role: 'seeker', label: 'Favorite', title: 'Colecțiile tale', description: 'Grupează proprietățile pentru vizionare, comparație sau discuții.', action: 'Creează o colecție', variant: 'collections' },
  'alert-detail': { role: 'seeker', label: 'Alertă salvată', title: '2 camere în Centru', description: '€450–€700 · mobilat · animale acceptate · numai cu istoric.', action: 'Editează alerta', variant: 'alert' },
  'visit-detail': { role: 'seeker', label: 'Vizionare', title: 'Vizionare la Lev Tolstoi 24/1', description: 'Sâmbătă, 18 iulie · 11:30 · proprietar confirmat.', action: 'Reprogramează', variant: 'calendar' },
  'my-offers': { role: 'seeker', label: 'Negociere', title: 'Ofertele mele', description: 'Urmărește ofertele trimise și răspunsurile proprietarilor.', action: 'Vezi proprietăți', variant: 'table' },
  'my-reports': { role: 'seeker', label: 'Siguranță', title: 'Raportările mele', description: 'Statusul informațiilor, anunțurilor sau recenziilor raportate.', action: 'Raportează o problemă', variant: 'cases' },
  corrections: { role: 'seeker', label: 'Date corecte', title: 'Solicitări de corectare', description: 'Urmărește completările și corectările trimise pentru dosare.', action: 'Solicită o corectare', variant: 'cases' },
  claim: { role: 'owner', label: 'Proprietate', title: 'Revendică o proprietate', description: 'Confirmă legătura cu o proprietate existentă fără a crea un duplicat.', action: 'Caută proprietatea', variant: 'verification' },
  'property-verification': { role: 'owner', label: 'Verificare', title: 'Verificarea proprietății', description: 'Documente, adresă și statutul confirmării pentru Lev Tolstoi 24/1.', action: 'Continuă verificarea', variant: 'verification' },
  'listing-performance': { role: 'owner', label: 'Analiză', title: 'Performanța anunțului', description: 'Vizualizări, salvări, lead-uri și comparație cu proprietăți similare.', action: 'Optimizează anunțul', variant: 'stats' },
  leads: { role: 'owner', label: 'Interes', title: 'Lead-uri și contacte', description: 'Persoane care au salvat, întrebat sau cerut o vizionare.', action: 'Exportă lista', variant: 'pipeline' },
  requests: { role: 'owner', label: 'Solicitări', title: 'Cereri primite', description: 'Vizionări, întrebări și documente solicitate de potențiali clienți.', action: 'Setează disponibilitatea', variant: 'table' },
  'owner-offers': { role: 'owner', label: 'Negociere', title: 'Oferte primite', description: 'Compară valoarea, termenii și statusul fiecărei oferte.', action: 'Configurează ofertele', variant: 'table' },
  calendar: { role: 'owner', label: 'Program', title: 'Calendarul proprietăților', description: 'Vizionări, expirări, publicări și lucrări programate.', action: 'Adaugă disponibilitate', variant: 'calendar' },
  'review-responses': { role: 'owner', label: 'Reputație', title: 'Răspunsuri la recenzii', description: 'Răspunde public și urmărește feedbackul legat de proprietăți.', action: 'Vezi ghidul de răspuns', variant: 'cases' },
  disputes: { role: 'owner', label: 'Transparență', title: 'Contestații și dispute', description: 'Cazuri deschise despre prețuri, istoric sau recenzii.', action: 'Deschide o contestație', variant: 'cases' },
  documents: { role: 'owner', label: 'Documente', title: 'Documentele proprietăților', description: 'Fișiere anonimizate, verificări și termene de valabilitate.', action: 'Încarcă document', variant: 'table' },
  'owner-profile': { role: 'owner', label: 'Identitate publică', title: 'Profilul tău de proprietar', description: 'Informațiile publice, ratingul și timpul mediu de răspuns.', action: 'Editează profilul', variant: 'profile' },
  archive: { role: 'owner', label: 'Arhivă', title: 'Proprietăți închiriate sau vândute', description: 'Anunțuri încheiate, rezultate și istoricul păstrat.', action: 'Exportă arhiva', variant: 'table' },
  'listing-status': { role: 'owner', label: 'Status anunț', title: 'Gestionează statutul anunțului', description: 'Marchează închiriat, vândut, expirat sau pregătește reînnoirea.', action: 'Actualizează statusul', variant: 'verification' },
  portfolio: { role: 'agent', label: 'Portofoliu', title: 'Portofoliul agenției', description: 'Proprietăți, statusuri, agenți responsabili și performanță.', action: 'Adaugă proprietate', variant: 'table' },
  'agent-leads': { role: 'agent', label: 'CRM', title: 'Lead-uri agenție', description: 'Pipeline comun pentru cereri, vizionări și oferte.', action: 'Adaugă lead', variant: 'pipeline' },
  members: { role: 'agent', label: 'Echipă', title: 'Membrii agenției', description: 'Roluri, portofolii alocate, activitate și disponibilitate.', action: 'Invită membru', variant: 'table' },
  roles: { role: 'agent', label: 'Acces', title: 'Roluri și permisiuni', description: 'Controlează accesul la lead-uri, documente și publicare.', action: 'Creează rol', variant: 'verification' },
  'agency-stats': { role: 'agent', label: 'Analiză', title: 'Statisticile agenției', description: 'Conversie, timp de răspuns, portofoliu și activitate pe agenți.', action: 'Descarcă raportul', variant: 'stats' },
  'agency-verification': { role: 'agent', label: 'Încredere', title: 'Verificarea agenției', description: 'Date juridice, membri confirmați și documente valabile.', action: 'Continuă verificarea', variant: 'verification' },
}

const roleMenu: Record<Role, Array<[string, string]>> = {
  seeker: [['Recomandări', '/recomandari'], ['Vizualizate recent', '/vizualizate-recent'], ['Colecții', '/colectii'], ['Alerte', '/cautari-salvate'], ['Vizionări', '/vizionari'], ['Oferte', '/ofertele-mele'], ['Raportări', '/raportarile-mele']],
  owner: [['Anunțuri', '/anunturile-mele'], ['Performanță', '/performanta-anunt'], ['Lead-uri', '/lead-uri'], ['Cereri', '/cereri'], ['Oferte', '/oferte'], ['Calendar', '/calendar'], ['Documente', '/documente'], ['Arhivă', '/arhiva']],
  agent: [['Portofoliu', '/portofoliu'], ['Lead-uri', '/agent-lead-uri'], ['Membri', '/membri-agentie'], ['Roluri', '/roluri-agentie'], ['Statistici', '/statistici-agentie'], ['Verificare', '/verificare-agentie']],
}

export function WorkspaceHubPage({ kind, ...shared }: SharedPageProps & { kind: WorkspaceKind }) {
  const info = pages[kind]
  return <div className={`hub-page role-${info.role}`}><div className='container hub-shell'>
    <aside className='hub-sidebar'><div><span>{info.role === 'seeker' ? 'AM' : info.role === 'owner' ? 'VI' : 'IC'}</span><strong>{info.role === 'seeker' ? 'Spațiul meu' : info.role === 'owner' ? 'Proprietăți' : 'Casa Nouă'}</strong></div><nav>{roleMenu[info.role].map(([label, path]) => <button type='button' onClick={() => shared.navigate(path)} key={path}>{label}</button>)}</nav><button type='button' onClick={() => shared.navigate('/dashboard')}><Icon name='arrow-right' className='back-icon' /> Dashboard</button></aside>
    <main className='hub-main'><header className='hub-header'><div><span className='eyebrow'>{info.label}</span><h1>{info.title}</h1><p>{info.description}</p></div><button className='button button-primary' type='button'>{info.action}</button></header><div className='hub-toolbar'><label><Icon name='search' size={18} /><input placeholder='Caută în această pagină' /></label><div><button type='button'><Icon name='filter' size={17} /> Filtre</button><select><option>Actualizate recent</option><option>Cele mai noi</option><option>După status</option></select></div></div><HubContent variant={info.variant} kind={kind} shared={shared} /></main>
  </div></div>
}

function HubContent({ variant, kind, shared }: { variant: Variant; kind: WorkspaceKind; shared: SharedPageProps }) {
  if (variant === 'properties') return <div className='hub-property-grid'>{properties.slice(0, 3).map((property) => <PropertyCard property={property} key={property.id} {...shared} />)}</div>
  if (variant === 'activity') return <div className='activity-timeline'>{[['Astăzi, 11:42', 'Ai deschis dosarul proprietății Lev Tolstoi 24/1', 'Istoric preț și recenzii'], ['Astăzi, 10:18', 'Ai aplicat filtre pentru chirie în Centru', '€450–€700 · 2 camere'], ['Ieri, 19:05', 'Ai comparat trei proprietăți', 'Centru și Râșcani'], ['14 iulie, 16:30', 'Ai salvat o căutare', 'Cu istoric · animale acceptate']].map(([date,title,detail]) => <article key={date + title}><span><Icon name='history' /></span><div><small>{date}</small><strong>{title}</strong><p>{detail}</p></div><button type='button'>Deschide</button></article>)}</div>
  if (variant === 'collections') return <div className='hub-collection-grid'>{[['Pentru vizionat', '6', properties[0].image], ['Finaliste', '3', properties[1].image], ['Pentru familie', '8', properties[2].image], ['Investiție', '4', properties[3].image]].map(([title,count,image]) => <article key={title}><img src={image} alt='' /><div><strong>{title}</strong><span>{count} proprietăți</span></div><button type='button'>Deschide</button></article>)}</div>
  if (variant === 'alert') return <AlertPanel shared={shared} />
  if (variant === 'calendar') return <CalendarPanel kind={kind} />
  if (variant === 'verification') return <VerificationPanel kind={kind} />
  if (variant === 'stats') return <StatsPanel />
  if (variant === 'pipeline') return <PipelinePanel />
  if (variant === 'profile') return <ProfilePanel />
  if (variant === 'cases') return <CasesPanel kind={kind} />
  return <RecordsTable kind={kind} />
}

function AlertPanel({ shared }: { shared: SharedPageProps }) { return <div className='hub-alert-panel'><section><span>Status alertă</span><strong>Activă</strong><p>Notificări instant pentru proprietăți noi și prețuri reduse.</p><div><span>Tip <b>Chirie</b></span><span>Sectoare <b>Centru, Râșcani</b></span><span>Buget <b>€450–€700</b></span><span>Camere <b>2</b></span></div></section><aside><h3>7 rezultate noi</h3>{properties.slice(0,2).map((property) => <button type='button' onClick={() => shared.navigate(`/proprietate/${property.slug}`)} key={property.id}><img src={property.image} alt='' /><span><strong>{property.address}</strong><small>€{property.price} · {property.district}</small></span><Icon name='arrow-right' /></button>)}</aside></div> }

function CalendarPanel({ kind }: { kind: WorkspaceKind }) { return <div className='hub-calendar'><div className='calendar-month'><header><button type='button'>‹</button><strong>Iulie 2026</strong><button type='button'>›</button></header><div className='week-labels'>{['L','M','M','J','V','S','D'].map((d,i) => <span key={d+i}>{d}</span>)}</div><div className='month-grid'>{Array.from({length:35},(_,i) => <button className={i === 18 ? 'active' : i === 16 || i === 22 ? 'has-event' : ''} type='button' key={i}>{i < 3 ? 28+i : i-2}</button>)}</div></div><aside><span>{kind === 'visit-detail' ? 'Vizionarea selectată' : 'Agenda zilei'}</span><h3>18 iulie</h3>{[['11:30','Vizionare · Lev Tolstoi'], ['15:00','Apel · Ana M.'], ['18:30','Vizionare · bd. Moscova']].map(([time,title]) => <article key={time}><b>{time}</b><strong>{title}</strong><button type='button'>Detalii</button></article>)}<div className='calendar-actions'><button type='button'>Reprogramează</button><button type='button'>Anulează</button></div></aside></div> }

function VerificationPanel({ kind }: { kind: WorkspaceKind }) { const items = kind === 'listing-status' ? [['Publicat','Activ acum','done'],['Marchează închiriat','Păstrează istoricul public','current'],['Marchează vândut','Adaugă prețul tranzacției',''],['Expirare','26 august 2026',''],['Reînnoire','Disponibilă cu 7 zile înainte','']] : [['Identitatea solicitantului','Confirmată','done'],['Adresa proprietății','Confirmată','done'],['Document de legătură','În analiză','current'],['Date cadastrale','Urmează',''],['Confirmare finală','Urmează','']]; return <div className='verification-workspace'><section><div className='verification-progress-ring'><strong>72%</strong><span>complet</span></div><h3>{kind === 'claim' ? 'Revendicare în progres' : 'Proces de verificare'}</h3><p>Nicio informație sensibilă nu va fi afișată public.</p></section><div>{items.map(([title,status,state],index) => <article className={state} key={title}><span>{state === 'done' ? <Icon name='check' /> : index+1}</span><div><strong>{title}</strong><small>{status}</small></div><button type='button'>{state === 'current' ? 'Continuă' : 'Detalii'}</button></article>)}</div></div> }

function StatsPanel() { return <div className='hub-stats'><div className='hub-stat-grid'>{[['Vizualizări','1.284','+12%'],['Salvări','86','+8%'],['Lead-uri','37','+14%'],['Vizionări','16','+3'],['Conversie','12,8%','+2,4 pp']].map(([label,value,change]) => <article key={label}><span>{label}</span><strong>{value}</strong><b>{change}</b></article>)}</div><section className='stats-chart-card'><header><div><h3>Interes în ultimele 30 de zile</h3><p>Vizualizări și contacte calificate</p></div><select><option>Toate proprietățile</option></select></header><div className='stats-line-chart'><svg viewBox='0 0 900 260' preserveAspectRatio='none'><path d='M0 230 C120 215 160 190 260 198 S390 142 490 155 S620 100 710 82 S820 64 900 25' /></svg></div></section></div> }

function PipelinePanel() { return <div className='hub-pipeline'>{[['Noi','12'],['Contactați','9'],['Vizionare','11'],['Ofertă','5']].map(([stage,count],column) => <section key={stage}><header><strong>{stage}</strong><span>{count}</span></header>{[0,1,2].map((item) => <article key={item}><span>{['AM','DP','VC'][(item+column)%3]}</span><div><strong>{['Ana M.','Dan P.','Victor C.'][(item+column)%3]}</strong><small>{['Chirie Centru','3 camere Râșcani','Toro Center'][(item+column)%3]}</small></div><button type='button'>•••</button></article>)}</section>)}</div> }

function ProfilePanel() { return <div className='public-profile-editor'><aside><span>VI</span><h3>Victor I.</h3><p>Proprietar verificat</p><b>★ 4,8 · 26 recenzii</b><button type='button'>Vezi profilul public</button></aside><section><h3>Informații publice</h3><label>Nume afișat<input defaultValue='Victor I.' /></label><label>Descriere<textarea defaultValue='Proprietar verificat, gestionez direct două apartamente în Chișinău.' /></label><div><label>Timp de răspuns<input defaultValue='aprox. 2 ore' /></label><label>Limbi<select><option>Română, rusă</option></select></label></div><button className='button button-primary' type='button'>Salvează modificările</button></section></div> }

function CasesPanel({ kind }: { kind: WorkspaceKind }) { return <div className='case-list'>{[['LOC-2481', kind === 'my-reports' ? 'Fotografii neactuale' : 'Corectare preț anterior', 'În analiză', 'Actualizat acum 2 ore'], ['REC-103', kind === 'disputes' ? 'Recenzie contestată' : 'Informație despre bloc', 'Informații solicitate', 'Actualizat ieri'], ['LOC-1934', 'Confirmare document', 'Rezolvat', '12 iulie 2026']].map(([id,title,status,date]) => <article key={id}><span><Icon name='file' /></span><div><small>{id}</small><strong>{title}</strong><p>{date}</p></div><b>{status}</b><button type='button'>Deschide cazul</button></article>)}</div> }

function RecordsTable({ kind }: { kind: WorkspaceKind }) { const rows = kind === 'members' ? [['Irina C.','Agent senior','12 proprietăți','Activ'],['Dan M.','Agent','8 proprietăți','Activ'],['Ana P.','Fotograf','5 ședințe','Invitat']] : kind === 'documents' ? [['Extras cadastral','Lev Tolstoi 24/1','Verificat','12 iul. 2026'],['Contract mandat','bd. Moscova 18/2','În analiză','15 iul. 2026'],['Proces-verbal','Toro Center','Expiră curând','30 iul. 2026']] : [['Lev Tolstoi 24/1','Ana M.','Vizionare','Nou'],['bd. Moscova 18/2','Radu C.','€115.000','În negociere'],['str. Grenoble 128','Elena S.','Mesaj','Răspuns trimis']]; return <div className='hub-records'><div className='hub-record-head'><span>Înregistrare</span><span>Proprietate / rol</span><span>Detaliu</span><span>Status</span><span>Acțiuni</span></div>{rows.map((row) => <article key={row[0]}>{row.map((cell) => <span key={cell}>{cell}</span>)}<button type='button'>Gestionează</button></article>)}</div> }
